[versions]
pluginVersion = "1.1.0-test"
agp = "8.10.0"
decompose = "3.2.2"
realm = "3.2.8-2"
kotlin = "2.2.0"
core-ktx = "1.15.0"
lifecycle-runtime-ktx = "2.8.7"
activity-compose = "1.9.3"
compose-bom = "2024.12.01"
datetime = "0.7.1"
ktor = "3.3.2"
uuid = "0.8.4"
jetbrains-compose = "1.7.0"
maven-publish = "0.30.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
decomposeCompose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
realm = { module = "com.infomaniak.realm.kotlin:library-base", version.ref = "realm" } # Realm Kotlin fork with support for Kotlin 2.2.x
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

[plugins]
com-android-library = { id = "com.android.library", version.ref = "agp" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
org-jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
org-jetbrains-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
io-realm-kotlin = { id = "com.infomaniak.realm.kotlin", version.ref = "realm" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
